 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run:  docker build -t ytdownloader-api
       - run: heroku container:push web -a ytdownloader-api
       - run: heroku container:release web -a ytdownloader-api
